version: "3"

services:
  pb:
    container_name: root-cellar-pb
    restart: always
    build: pb
    ports:
      - 4006:8090
    volumes:
      - ./pb/pb_data:/usr/local/bin/pb_data
      - ./pb/pb_migrations:/usr/local/bin/pb_migrations
      - ./pb/pb_hooks:/usr/local/bin/pb_hooks
  web:
    build: ./web
    entrypoint: npm run serve
    restart: always
    ports:
      - 4005:4005
